Update CSI - Process - Set Live Presentation Time --farsi-ir.md
cs-internship/cs-internship-spec pull request #192
Opened 2024-09-17 20:32 UTC by faeghehmohammadian

این داکیومنت بر اساس متن لینک زیر آپدیت شده است: https://t.me/c/1273069838/31071/38120

این به‌روزرسانی برای رفع ابهاماتی که در فرایند ارائه آنلاین وجود داشت، انجام شده است.

2024-09-17 20:41 UTC, faeghehmohammadian commented
@zahra-ahangari  please review these updates
@Ali-Sdg90 please review these updates

2024-09-30 12:44 UTC, zahra-ahangari commented
Please mention the code owner for review after all other reviewers have approved the changes. I'll review it in the final stage and merge it afterward if approved.
@faeghehmohammadian

2024-09-30 16:24 UTC, Ali-Sdg90 requested changes

2024-09-30 16:24 UTC, Ali-Sdg90 commented on processes/documents/CSI - Process - Set Live Presentation Time --farsi-ir.md
> +حضور کوردینیتور در ارائه آنلاین الزامی نیست. اینترن باید ارائه خود را در بستر لینکدین انجام دهد و پس از آن، فایل ضبط‌شده جلسه و تصویر لیست شرکت‌کنندگان را به کوردینیتور ارسال کند. همچنین، پس از پایان
اینترن ارائه خود را در بستر لینکدین آغاز کرده و همزمان، آن را به صورت لوکال ضبط می‌کند. شرکت‌کنندگان از طریق بخش نظرات مربوط به ارائه، حضور خود را اعلام می‌نمایند. پس از پایان ارائه، اینترن عکس از کامنت‌های گذاشته شده در ارائه میگیرد که نشان میدهد چه کسایی در ارائه شرکت کرده‌اند و آن عکس را در گروه "CS Internship - Coordination" برای کوردینیتور خود ارسال می‌کند. این کار به کوردینیتور کمک می‌کند تا از حضور افراد در ارائه مطلع شود. بنابراین لزومی به حضور کوردینیتور در ارائه‌ی اینترن‌ها نیست.

پس از پایان ارائه، اینترن موظف است فایل ضبط‌شده‌ی ارائه خود را به همراه عنوان و توضیحات مرتبط، در گروه "CS Internship - Coordination" ارسال و کوردینیتور خود را تگ کند. کوردینیتور ویدئوی ارائه را به همراه عنوان و توضیحات مربوطه در کانال یوتیوب CS Internship بارگذاری می‌نماید. فرآیند ارائه اینترن با آپلود ویدئوی ارائه در کانال یوتیوب به پایان می‌رسد.

2024-09-30 16:24 UTC, Ali-Sdg90 commented on processes/documents/CSI - Process - Set Live Presentation Time --farsi-ir.md
> +حضور کوردینیتور در ارائه آنلاین الزامی نیست. اینترن باید ارائه خود را در بستر لینکدین انجام دهد و پس از آن، فایل ضبط‌شده جلسه و تصویر لیست شرکت‌کنندگان را به کوردینیتور ارسال کند. همچنین، پس از پایان
فکر کنم این متنی که نوشتم با متن گذاشته شده جایگذین بشه بهتر باشه

2024-09-30 16:24 UTC, Ali-Sdg90 commented on processes/documents/CSI - Process - Set Live Presentation Time --farsi-ir.md
> +ارائه‌های آنلاین به صورت زنده برگزار می‌شوند و کیفیت این ارائه‌ها نشان‌دهنده سطح مطالعه و آمادگی اینترن در یک استپ است. برای برگزاری این ارائه‌ها، هماهنگی بین منتورها و اینترن ارائه‌دهنده ضروری است ت
پیشنهاد میکنم متن پایین جایگذین متن بالایی بشه

2024-09-30 16:24 UTC, Ali-Sdg90 commented on processes/documents/CSI - Process - Set Live Presentation Time --farsi-ir.md
> +ارائه‌های آنلاین به صورت زنده برگزار می‌شوند و کیفیت این ارائه‌ها نشان‌دهنده سطح مطالعه و آمادگی اینترن در یک استپ است. برای برگزاری این ارائه‌ها، هماهنگی بین منتورها و اینترن ارائه‌دهنده ضروری است ت
پیشنهاد میکنم متن پایین جایگذین متن بالایی بشه

2024-10-03 09:33 UTC, faeghehmohammadian commented on processes/documents/CSI - Process - Set Live Presentation Time --farsi-ir.md
> +ارائه‌های آنلاین به صورت زنده برگزار می‌شوند و کیفیت این ارائه‌ها نشان‌دهنده سطح مطالعه و آمادگی اینترن در یک استپ است. برای برگزاری این ارائه‌ها، هماهنگی بین منتورها و اینترن ارائه‌دهنده ضروری است ت
done

2024-10-03 09:33 UTC, faeghehmohammadian commented on processes/documents/CSI - Process - Set Live Presentation Time --farsi-ir.md
> +ارائه‌های آنلاین به صورت زنده برگزار می‌شوند و کیفیت این ارائه‌ها نشان‌دهنده سطح مطالعه و آمادگی اینترن در یک استپ است. برای برگزاری این ارائه‌ها، هماهنگی بین منتورها و اینترن ارائه‌دهنده ضروری است ت
done

2024-10-07 15:21 UTC, zahra-ahangari approved these changes

2024-10-07 15:38 UTC, Ali-Sdg90 approved these changes

2024-10-07 15:46 UTC, merged