Update CSI - Process - Update Interns Profile --farsi-ir.md
cs-internship/cs-internship-spec pull request #198
Opened 2024-10-21 04:16 UTC by shab-sa

Adding what points should be inserted Adding what points should be inserted in intern's profile about their activities.in intern's profile about their activities:
.1 چنانچه اینترن نتواند استپ خود را با توجه به تعهدی که مشخص کرده است، به اتمام برساند و نیاز به تغییر تعهد داشته باشد، می‌تواند تعهد خود را تغییر داده و در خصوص تعداد تغییرات تعهد، هیچ محدودیتی وجود ندارد. اما چنانچه اینترن زودتر از تعهدی که مشخص کرده است، استپ موردنظر را به اتمام برساند و درخواست تغییر تعهد به زمانی جلوتر را داشته باشد، این امر در طول گذراندن استپ‌های اینترن، فقط یکبار امکانپذیر است. تغییر تعهد در پروفایل اینترن ثبت خواهد ‌شد.
2. چنانچه اینترن در استپ صفر، با افراد موردنظر زمانی را برای صحبت، مشخص کرده باشد اما در آن زمان حاضر نشود، این مورد در پروفایل اینترن ثبت خواهد شد.
3. چنانچه تعهد مشخص شده توسط اینترن سپری شود و اینترن پس از سپری شدن تعهد قبلی، تعهد جدید خود را مشخص کند، این مورد در پروفایل او ثبت خواهد شد.

2024-10-21 04:19 UTC, shab-sa commented
@Marirood  Can you please review the changes I made in this document and give me your feedbacks?

2024-11-01 15:27 UTC, shab-sa commented
@zahra-ahangari  can you please review the changes I made to this document and if this is ok, merge this pull request.

2024-11-08 00:33 UTC, zahra-ahangari commented
Thank you. @shab-sa  
I've reviewed the changes and left some comments. Please check them out.

2024-11-20 22:22 UTC, zahra-ahangari requested changes

2024-11-24 04:32 UTC, shab-sa commented
Thank You Zahra. I edited the file based on your comments. Can you please Check it again @zahra-ahangari .

2024-11-25 09:25 UTC, ZahraaaRezaeiii approved these changes

2024-12-02 10:38 UTC, zahra-ahangari approved these changes

2024-12-02 10:39 UTC, merged