Update mentoring-workshops-instruction.md
cs-internship/cs-internship-spec pull request #201
Opened 2024-11-04 12:58 UTC by zahramohammadi078

Add this text as a note to the document 'In mentorship workshop meetings, you need to turn on your camera, and the meetings will be held visually.'  and change the word 'mentoring intern' to 'coordinator.

2024-11-04 13:04 UTC, zahramohammadi078 commented
@Ali-Sdg90 
@zahra-ahangari 
Please review this document

2024-11-08 15:12 UTC, Ali-Sdg90 requested changes
Commented based on the first changes

2024-11-08 15:12 UTC, Ali-Sdg90 commented on courses/mentoring-workshops-instruction.md
> +2. You should ask your coordinator to set a workshop reservation for each video's report. You will attend each mentorship workshop only for one report.
اینجا هم لازمه گفته بشه خودتون برای خودتون جلسه رو ست میکنین

2024-11-08 15:12 UTC, Ali-Sdg90 commented on courses/mentoring-workshops-instruction.md
> +2. Send the report of the first video to your coordinator and request your coordinator to schedule a mentorship session for your report.
request your coordinator to schedule a mentorship session for your report.

این هم لازمه آپدیت بشه که خود اینترن جلسه رو واسه خودش ست کنه

2024-11-08 15:12 UTC, Ali-Sdg90 commented on courses/mentoring-workshops-instruction.md
>         	- So, it is almost 50-50 to get a chance to participate in a workshop for two reports.
این قسمت لزومی نداره اصلا باشه. فکر کنم پاکش کنی بهتر باشه

2024-11-08 15:12 UTC, Ali-Sdg90 commented on courses/mentoring-workshops-instruction.md
>  	- **Positive** assessment result, means then you can start to watch the next video, wirte its report and send it to your mentoring inter before the setteled mentorship workshop.
mentoring inter -> Coordinator

2024-11-08 15:12 UTC, Ali-Sdg90 commented on courses/mentoring-workshops-instruction.md
تو قسمت Improtant Note اینم بگو که برای اولین فیلم دوره ی کامیونیکیشن نمیتونین از حالت Alternative استفاده کنین و لازمه براش حتما یک جلسه ست کنین.

2024-11-25 12:15 UTC, zahra-ahangari commented on courses/mentoring-workshops-instruction.md
> +- Thirdly, you have to ask your coordinator to send you the report template to wirte your reports about the videos.
نشونی فایل:
[processes/documents/CSI - Template - Mentor Training Report - Farsi.docx](https://github.com/cs-internship/cs-internship-spec/blob/master/processes/documents/CSI%20-%20Template%20-%20Mentor%20Training%20Report%20-%20Farsi.docx)

فایل رو هم به این شکل که توی عکس مشخص کردم می‌شه دانلود کرد:
![Mentor Training Report Template image](https://github.com/user-attachments/assets/dcb164c8-21a4-4d4e-87aa-da92fbdac983)

2024-11-25 12:15 UTC, zahra-ahangari commented on courses/mentoring-workshops-instruction.md
> +- Thirdly, you have to ask your coordinator to send you the report template to wirte your reports about the videos.
@zahramohammadi078

2024-11-25 12:18 UTC, zahra-ahangari reviewed
I've added the template file link in the repo and it's available now for your use case.
@zahramohammadi078 
cc: @Ali-Sdg90

2024-11-25 15:45 UTC, zahra-ahangari approved these changes

2024-12-16 10:00 UTC, Ali-Sdg90 approved these changes
LGTM, Thanks

2024-12-16 15:35 UTC, merged