Create CSI - Meeting Coordination for Interns --farsi-ir.md
cs-internship/cs-internship-spec pull request #206
Opened 2024-11-11 04:44 UTC by shab-sa

Write a new Document to guide interns about meetings in CS Internships.

2024-11-11 04:45 UTC, shab-sa commented
@Ali-Sdg90 Can you please review the document I wrote about Meeting Coordination for Interns and give me your feedbacks.

2024-11-19 10:40 UTC, Ali-Sdg90 requested changes
Review Document Part 1

مرسی شبنم خسته نباشی خیلی خوب نوشتیش. چندتا کامنت اصلاح کوچولو رو داکیومنت گذاشتم. لطفا چکشون کن. 

یه داکیومنت هم بهش چسبوندم. این هم لطفا به داکیومنت اضافش کن😁

مرسی و خسته نباشی :)

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +به صورت کلی دو نوع جلسه برای اینترن‌های تازه‌وارد در دوره CS Internship وجود دارد که در ادامه معرفی می‌شوند. دوره CS Internship شامل 2 مسیر کلی فنی و مهارت‌های نرم است که بابت هر مسیر جلساتی به صورت
و در مسیر مهارت‌های نرم، کارگاه‌های مربی‌گری که در هر استپ لازم اینترن در یک یا دو جلسه این کارگاه ‌ها شرکت کند.
-->

تو همه‌ی استپ‌ها ۲ ویدئو یا ۰ ویدئو هست. اگه منظورت شرکت در یک جلسه کارگاه تو حالت استثنا بود، فکر کنم این خیلی خوب منظور رو نمیرسونه. من که این رو میخونم برام معنی میده که در استپ‌ها یا یک جلسه کارگاه دارم یا دوتا.
فکر کنم اینجوری بهتر باشه:

در مسیر مهارت‌های نرم، جلسات کارگاه‌های مربی‌گری به صورت فیلم ضبط شده در استپ‌های مختلف دوره‌ها ارائه شده‌اند. اینترن‌ها لازم است برای این ویدئوها، در جلسات کارگاه‌ها شرکت کنند.

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +این جلسات توسط منتورهای فتی هر یک از دوره‌های CS Internship در زمان‌های ثابتی در هر هفته برگزار می‌شود که لیست این زمان‌ها در گروه Coordination در تلگرام به صورت پین شده وجود دارد. در دوره CS Interns
بهتره اسم کامل گروه کوردینیشن رو بذاری (CS Internship - Coordination) و بگی تو ساب گروه Meeting پیام پین شده رو برای لیست منتور‌های فنی و زمان جلسات ببینین

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +#جلسات فنی
اینجا واسه اینکه متن رو گنده و هدینگ کنی، لازمه بعد # یه اسپیس هم بذاری

# سلام
`# سلام`

-----

## سلام
`## سلام`

-----

### سلام
`### سلام`

-----

#### سلام
`#### سلام`

-----

##### سلام
`##### سلام`

-----

###### سلام
`###### سلام`

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +این جلسات توسط منتورهای فتی هر یک از دوره‌های CS Internship در زمان‌های ثابتی در هر هفته برگزار می‌شود که لیست این زمان‌ها در گروه Coordination در تلگرام به صورت پین شده وجود دارد. در دوره CS Interns
در دوره CS Internship به منتور یا دستیارمنتوری که جلسات فنی برگزار می‌کند، اصطلاحاً منتورفنی گویند.

-->

در **_برنامه‌ی_** CS Internship به **_منتورهایی_** که جلسات فنی برگزار می‌کند، اصطلاحاً منتورفنی **_می‌گویند_**.

چون کاندین منتور - منتور - دستیارمنتور میتونه منتور فنی باشه، اینجا فقط بگیم منتور کافی هستش. توضیحات نقش‌ها تو یه داکیومنت دیگه کامل گذاشته میشه. تو اون با تفاوت اینا اشنا میشم

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
دو جا تو این متن «دوره CS Internship» اومده. لازمه برنامه باشه

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد.

-->

در کنار مباحث فنی، تمرکز اصلی برنامه CS Internship بر آماده‌سازی اینترن‌ها برای ورود به بازار کار در شرکت‌های معتبر است.

یکم جمله‌بندی این بهتره

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
در هر استپ اینترن‌ها 2 ویدیو از این مجموعه را تماشا کرده و گزارشی را بر مبنای تمپلیت موجود برای نوشتن گزارش، آماده و برای کوردینیتور خود ارسال می‎کنند.
 
 -->
 
 تو هر استپ ۲ ویدئو وجود نداره. چنتا استپ آخر بعضی از دوره‌ها ویدئو نداره. اینجا فقط بگیم در استپ‌ها برای اینترن‌ها ویدئوهایی از این مجموعه گذاشته شده که...

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
سپس برای اسپرینت بعد جلسه‌ای ست می‌نمایند.

-->

سپس برای اسپرینت بعد (هفته‌ی بعد) جلسه‌ای ست می‌نمایند.

چون هنوز تعریفی از اسپرینت نگفتیم تو پرانتز لازمه این رو بیاریم. بعدا پایین تر توضیح اسپرینت رو میگیم

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
به جلساتی که در مورد تماشای ویدیو‌ها برگزار می‌شود، «کارگاه‌های مربی‌گری» می‌گویند.

-->

کارگاه‌های مربیگری فکر کنم فقط به ۱۲ فیلم انتهایی میگیم. دوره‌ی اول کارگاه ارتباطات هست. بهتره اینجا بگیم «کارگاه منتورشیپ»

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
این جلسات به صورت تصویری برگزار می‌شوند

-->

اینجا یکم کامل‌تر بگیم این جلسات در برنامه‌ی ماکروسافت تیمز به صورت تصویر برگزار میشه. من که ندونم جلسات چی هست، فکر میکنم حضوری هستش

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +این جلسات نیز در نرم‌افزار تیمز برگزاری می‌شود اما نحوه شرکت  در آن با جلسات فنی کمی متفاوت است. برای شرکت در این جلسات شما باید به کانال «CS Internship – Mentorship Workshop» دسترسی داشته باشید. برا
برای شرکت در این جلسات شما باید به کانال «CS Internship – Mentorship Workshop» دسترسی داشته باشید.

-->

برای شرکت در این جلسات شما باید به کانال **_در تیمز_** «CS Internship – Mentorship Workshop» دسترسی داشته باشید.

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +این جلسات نیز در نرم‌افزار تیمز برگزاری می‌شود اما نحوه شرکت  در آن با جلسات فنی کمی متفاوت است. برای شرکت در این جلسات شما باید به کانال «CS Internship – Mentorship Workshop» دسترسی داشته باشید. برا
یه اشاره‌ای هم بشه که جلسات حداکثر نیم ساعت هست

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +- **گزارش هفتگی:** شامل تاریخ پست‌ها، لینک پست‌ها و تمام فعالیت‌های مربوط به اینترن در طول هفته است که در قالب یک فایل ورد یا اکسل توسط خود او تهیه و به کارآموزمنتور ارسال می‌شود.
کارآموزمنتور --> کوردینیتور

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +#نحوه هماهنگی جلسات
میخوای قسمت #نحوه هماهنگی جلسات  رو از اینجا حذف کن و جاش این متنی که تو ریپلای این پیام هست رو بگذار.

من یه فیلم ۳۰ دقیقه‌ای رو یوتیوب برای آموزش ست کردن جلسه آپلود کرده بودم. چند روز پیش زیرنویس فارسی این ویدئو رو از یوتیوب گرفتم، بعد کل چیزهایی که گفته بودم رو در قالب متن به ChatGPT دادم و ازش خواستم تبدیل به داکیومنتش کنه. چند ساعت باهاش ور رفتم و درنهایت تونستم ساختاربندیش رو اوکی کنم. چیزهایی که تو این متن گتفه شده ۹۹٪ درست هست. فقط ممکنه قسمتیش باشه که اشتباه داشته باشه. من هم چکش کردم. لطفا تو هم یه چکش بکن و اگه اوکی هست، به داکیومنت اضافش کن. مرسی :)

2024-11-19 10:40 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +#نحوه هماهنگی جلسات
Ali Sadeghi, [21/08/1403 01:23 ق.ظ]
## مقدمه و معرفی ابزار Azure Board

Azure Board یک ابزار قدرتمند برای مدیریت پروژه‌ها و تسک‌ها است که توسط تیم‌های مختلف، از جمله تیم CS Internship، مورد استفاده قرار می‌گیرد. این ابزار به کاربران اجازه می‌دهد تا به‌صورت دقیق و منظم کارهای خود را برنامه‌ریزی کنند، جلسات فنی و کارگاه‌ها را تنظیم نمایند و پیشرفت خود را پیگیری کنند.

در برنامه CS Internship، Azure Board برای مدیریت موارد زیر استفاده می‌شود:

- جلسات فنی: جلساتی که در آن منتورهای فنی به بررسی و آموزش مسائل تخصصی مرتبط با دوره‌های آموزشی می‌پردازند.
- کارگاه‌ها: جلساتی که در آن مهارت‌های نرم یا مدیریتی مانند ارتباطات یا کوچینگ آموزش داده می‌شود.
- مصاحبه‌ها و ارزیابی‌ها: برای اینترن‌های جدید یا ارزیابی عملکرد آن‌ها.

---

## چرا از Azure Board استفاده می‌کنیم؟

پیش از استفاده از Azure Board، هماهنگی جلسات فنی و کارگاه‌ها به‌صورت دستی و از طریق پیام‌رسانی در گروه‌های مختلف انجام می‌شد. این فرآیند زمان‌بر بود و احتمال بروز خطا در آن وجود داشت. با استفاده از Azure Board، اینترن‌ها اکنون قادر هستند به‌صورت مستقل جلسات خود را تنظیم کنند. این تغییر مزایای زیر را به همراه داشته است:

- سرعت و دقت بیشتر در هماهنگی جلسات.
- امکان مدیریت مستقیم تسک‌ها توسط اینترن‌ها.
- افزایش شفافیت در فرآیندها.

---

## دسترسی به Azure Board

دسترسی لازم به Azure Board از طریق ایمیل Outlook شما فراهم شده است. لینکی که برایتان ارسال شده است، شما را مستقیماً به صفحه‌ی مربوط به برنامه CS Internship هدایت می‌کند. با کلیک بر روی این لینک، وارد محیط Azure Board خواهید شد.

---

## ساختار کلی Azure Board

پس از ورود به Azure Board، صفحه‌ای شامل چندین ستون مشاهده خواهید کرد. هر ستون نشان‌دهنده وضعیت یک تسک است:

- To Do: تسک‌هایی که هنوز شروع نشده‌اند.
- In Progress: تسک‌هایی که در حال انجام هستند.
- Done: تسک‌هایی که تکمیل شده‌اند.

هر تسک (Task) معمولاً بخشی از یک Backlog است. Backlog مجموعه‌ای از تسک‌های مرتبط با یک هدف خاص است. برای مثال، یک Backlog ممکن است شامل تمامی تسک‌های مربوط به جلسات فنی یک هفته باشد.

---

## اسپرینت (Sprint) چیست؟

در سیستم Azure Board، کارها در بازه‌های زمانی مشخصی به نام اسپرینت (Sprint) برنامه‌ریزی می‌شوند. هر اسپرینت معمولاً یک هفته طول می‌کشد و تمامی تسک‌هایی که باید در آن هفته انجام شوند، در اسپرینت مربوطه قرار می‌گیرند.

برای مثال:
- اگر اسپرینت ۲۴۰ از تاریخ ۲ جولای تا ۸ جولای باشد، تمامی کارهایی که باید در این بازه زمانی انجام شوند، در این اسپرینت قرار دارند.

اینترن‌ها باید اطمینان حاصل کنند که جلساتی که برای خود تنظیم می‌کنند، در اسپرینت جاری قرار داشته باشند.

---

## فیلتر کردن Backlogs

برای نمایش فقط Backlogهای مربوط به جلسات فنی یا کارگاه‌ها، می‌توانید از قابلیت فیلتر کردن استفاده کنید:

1. روی گزینه فیلتر کلیک کنید.
2. انتخاب کنید که فقط Backlogهای مربوط به "Technical Sessions" (جلسات فنی) یا "Mentorship Workshops" (کارگاه‌ها) نمایش داده شوند.

این قابلیت کمک می‌کند تا سریع‌تر بتوانید جلسات مورد نظر خود را پیدا کنید.

---

## نحوه‌ی ست کردن جلسه‌ی فنی در Azure Board

### قدم اول: ورود به Azure Board و فیلتر کردن تسک‌ها

1. ورود به Azure Board:
   - ابتدا از طریق لینکی که به ایمیل شما ارسال شده است، وارد Azure Board شوید. این لینک شما را مستقیماً به صفحه‌ی مربوط به برنامه CS Internship هدایت می‌کند.
   - پس از ورود، محیط Azure Board شامل ستون‌های مختلف مانند To Do، In Progress و Done قابل مشاهده خواهد بود.

2. فیلتر کردن تسک‌ها:
   - برای نمایش فقط تسک‌های مربوط به جلسات فنی، باید از قابلیت فیلتر کردن استفاده کنید.
   - روی گزینه Filter کلیک کنید و انتخاب کنید که فقط تسک‌های مربوط به "Technical Sessions" نمایش داده شوند.
   - حالا فقط جلسات فنی در لیست شما نمایش داده خواهند شد.

---

### قدم دوم: پیدا کردن جلسه‌ی فنی مناسب

1. بررسی Backlog جلسات فنی:
   - پس از فیلتر کردن، لیستی از جلسات فنی موجود را مشاهده خواهید کرد. هر جلسه فنی در قالب یک تسک مشخص شده است.
   - هر تسک شامل اطلاعاتی مانند نام منتور (Mentor)، موضوع جلسه، تاریخ و زمان برگزاری است.

2. انتخاب جلسه مناسب:
   - برای انتخاب جلسه‌ای که با نیازهای شما همخوانی دارد، باید موضوع و زمان جلسات را بررسی کنید.
   - برای مثال، اگر شما یک اینترن دوره وب هستید و به دنبال جلسه‌ای مرتبط با برنامه‌نویسی وب هستید، باید جلسه‌ای را انتخاب کنید که منتور آن متخصص در وب باشد.

---

### قدم سوم: اضافه کردن نام خود به لیست شرکت‌کنندگان

Ali Sadeghi, [21/08/1403 01:23 ق.ظ]
1. باز کردن تسک مربوطه:
   - روی عنوان تسک کلیک کنید تا جزئیات آن باز شود.
   - در قسمت توضیحات تسک، راهنمایی‌هایی برای وارد کردن اطلاعات وجود دارد.

2. وارد کردن اطلاعات طبق الگو:
   - در اولین ردیف خالی موجود در لیست شرکت‌کنندگان، اطلاعات خود را طبق الگوی زیر وارد کنید:
     - نام اینترن
     - دوره (مثلاً دوره وب)
     - شماره استپ (مثلاً استپ ۵)
     - آدرس ایمیل
   - دقت کنید که اطلاعات خود را دقیقاً طبق الگو وارد کنید تا هماهنگی‌ها بدون مشکل انجام شود.

3. ظرفیت جلسات:
   - هر جلسه فنی معمولاً ظرفیت محدودی دارد (معمولاً ۴ نفر). قبل از وارد کردن اطلاعات خود، مطمئن شوید که ظرفیت خالی وجود دارد.

---

### قدم چهارم: آپلود گزارش هفتگی

1. آپلود گزارش هفتگی:
   - بعد از وارد کردن اطلاعات خود، لازم است گزارش هفتگی خود را نیز آپلود کنید.
   - برای این کار به بخش Attachments بروید و فایل گزارش خود را آپلود نمایید.
   - گزارش هفتگی شما توسط منتور بررسی خواهد شد تا بتواند بهترین راهنمایی‌ها را در جلسه ارائه دهد.

---

### قدم پنجم: تأیید نهایی

1. پس از وارد کردن اطلاعات و آپلود گزارش:
   - روی گزینه‌ی Save & Close کلیک کنید.
2. حالا شما به لیست شرکت‌کنندگان آن جلسه اضافه شده‌اید و منتور می‌تواند گزارش شما را بررسی کند.

---

## نحوه‌ی ست کردن جلسه‌ی کارگاه در Azure Board

### قدم اول: ورود به Azure Board و فیلتر کردن تسک‌ها

1. ورود به Azure Board:
   - ابتدا از طریق لینکی که به ایمیل شما ارسال شده است، وارد Azure Board شوید.
   
2. فیلتر کردن تسک‌ها:
   - برای اینکه فقط تسک‌های مربوط به جلسات کارگاه نمایش داده شوند، باید از قابلیت فیلتر کردن استفاده کنید.
   - روی گزینه‌ی Filter کلیک کنید و انتخاب کنید که فقط تسک‌های مربوط به "Mentorship Workshops" نمایش داده شوند.


## نحوه‌ی ست کردن جلسه‌ی کارگاه در Azure Board

### قدم اول: ورود به Azure Board و فیلتر کردن تسک‌ها

1. ورود به Azure Board:
   - ابتدا از طریق لینکی که به ایمیل شما ارسال شده است، وارد Azure Board شوید. این لینک شما را مستقیماً به صفحه‌ی مربوط به برنامه CS Internship هدایت می‌کند.
   - پس از ورود، محیط Azure Board را مشاهده خواهید کرد که شامل ستون‌های مختلفی مانند To Do، In Progress، و Done است.

2. فیلتر کردن تسک‌ها:
   - برای اینکه فقط تسک‌های مربوط به جلسات کارگاه نمایش داده شوند، باید از قابلیت فیلتر کردن استفاده کنید.
   - روی گزینه‌ی Filter کلیک کنید و انتخاب کنید که فقط تسک‌های مربوط به "Mentorship Workshops" نمایش داده شوند.
   - حالا فقط جلسات کارگاه در لیست شما نمایش داده خواهند شد.

---

### قدم دوم: پیدا کردن جلسه‌ی کارگاه مناسب

1. بررسی Backlog جلسات کارگاه:
   - پس از فیلتر کردن، لیستی از جلسات کارگاه موجود را مشاهده خواهید کرد. هر جلسه کارگاه در قالب یک تسک مشخص شده است.
   - هر تسک شامل اطلاعاتی مانند نام منتور (Mentor)، موضوع جلسه، تاریخ و زمان برگزاری است.

2. انتخاب جلسه مناسب:
   - برای انتخاب جلسه‌ای که با نیازهای شما همخوانی دارد، باید موضوع و زمان جلسات را بررسی کنید.
   - فرض کنید شما فیلم شماره ۲ دوره ارتباطات (Communication) را دیده‌اید و حالا می‌خواهید در جلسه مربوطه شرکت کنید. فرضاً یک تسک با عنوان "Communication Workshop 240" وجود دارد که توسط منتور "علی صادقی" برگزار می‌شود.

---

### قدم سوم: اضافه کردن نام خود به لیست شرکت‌کنندگان

1. باز کردن تسک مربوطه:
   - روی عنوان تسک کلیک کنید تا جزئیات آن باز شود.
   
2. وارد کردن اطلاعات طبق الگو:
   - در اولین ردیف خالی موجود در لیست شرکت‌کنندگان، اطلاعات خود را طبق الگوی زیر وارد کنید:
     - نام اینترن
     - دوره (مثلاً دوره ارتباطات)
     - شماره استپ (مثلاً استپ ۴)
     - آدرس ایمیل
   - دقت کنید که اطلاعات خود را دقیقاً طبق الگو وارد کنید تا هماهنگی‌ها بدون مشکل انجام شود.

3. ظرفیت جلسات:
   - هر جلسه کارگاه معمولاً ظرفیت محدودی دارد (معمولاً ۴ نفر). قبل از وارد کردن اطلاعات خود، مطمئن شوید که ظرفیت خالی وجود دارد.

---

### قدم چهارم: آپلود گزارش هفتگی

1. آپلود گزارش هفتگی:
   - بعد از وارد کردن اطلاعات خود، لازم است که گزارش هفتگی خود را نیز آپلود کنید.
   - برای این کار به بخش Attachments بروید و فایل گزارش خود را آپلود کنید.
   - گزارش هفتگی شما توسط منتور بررسی خواهد شد تا بتواند بهترین راهنمایی‌ها را در جلسه ارائه دهد.

---

### قدم پنجم: تأیید نهایی

1. پس از وارد کردن اطلاعات  [...]

2024-11-19 10:50 UTC, Ali-Sdg90 commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +#نحوه هماهنگی جلسات
[doc.txt](https://github.com/user-attachments/files/17813954/doc.txt)

فایل .txt این قسمت دایکومنت

2024-12-16 10:21 UTC, Ali-Sdg90 commented
> سلام شبنم خسته نباشی. خیلی خیلی داکیومنت خوبی شده. من ۴ کامنت کوچولو رو داکیومنت گذاشتم و پول ریکوئست رو اپرو کردم. لطفا این ۴ مورد رو اصلاح کن و به زهرا آهنگری برای ریویو و مرج بده.
> 
> راستی. لطفا تو داکیومنت قبل از اینکه راجب Azure و اینا توضیح بده، بگو یه فیلم برای توضیحات کار با Azure توسط برنامه ضبط شده. میتونین این فیلم رو ببینین یا توضیحات بولت پوینتی اون ویدئو رو اینجا ببینین. لینک ویدئو هم به صورت هایپرلینک تو این متن بگذار: https://youtu.be/pRCOpFa5XlI?si=DOsvRpgvQCDFQwiH
> 
> بازم دمت گرم. خیلی خوب نوشتیش :)

@shab-sa

2024-12-18 04:33 UTC, shab-sa commented
@zahra-ahangari  Can you please review the document I wrote about Meeting Coordination for Interns and give me your feedbacks.

2025-01-20 13:21 UTC, zahra-ahangari reviewed
ممنون از داکیومنتی که نوشتی شبنم. به نظرم برای نسخه‌ی اولیه خیلی داکیومنت خوبی شده.
و ممنون از شما علی بابت ریویو و نکاتی که پیش از من اشاره کرده بودی.
@Ali-Sdg90 

من چند تا کامنت گذاشتم که فعلا بتونی اون‌ها رو پیش ببری شبنم جان، اما هنوز نتونستم تا انتهای داکیومنت رو دقیق بخونم و تمام نکاتم رو بگم. این رو در اسرع وقت انجام و اطلاع می‌دم بهت.
@shab-sa

2025-01-20 13:21 UTC, zahra-ahangari commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +در کنار مباحث فنی تمرکز اصلی دوره CS Internship روی تربیت و آمادگی اینترن‌ها برای ورود به بازار کار قرار دارد. لازمه اصلی این امر تسلط و کسب مهارت‌های نرم برای هر اینترن است. در همین راستا در دوره CS
اسم «کارگاه‌های مربی‌گری» اسم و دقیقی نیست از اونجایی که اسم هر دوره متفاوته و اسم یکی از اون دوره‌ها مبانی مربی‌گریه، دیگری مربوط به مبانی ارتباطاته اگر اشتباه نکنم. بنابراین چنین اسمی اینجا استفاده نشه به نظرم بهتره. یا اگر علت خاصی به نظرت می‌رسه که لازمه باشه، روش صحبت کنیم.
@shab-sa

2025-01-20 13:21 UTC, zahra-ahangari commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +
در برنامه‌ی سی‌اس از برد برای مدیریت طیف گسترده‌تری از کارهایی که اینجا آوردی استفاده می‌شه که همه‌ش اینجا آورده نشده. به نظرم یا همه‌ی دسته‌ها باید آورده بشه که لزومی نداره به نظرم (چون در حال تغییره). یا می‌شه مشخصا بگیم که به عنوان نمونه این دسته‌ها از جمله مواردی هستن که بابتشون از برد استفاده می‌کنیم.
@shab-sa

2025-01-20 13:21 UTC, zahra-ahangari commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +
بازه‌ی اسپرینت در مجموعه‌های مختلف می‌تونه متفاوت باشه. کلمه‌ی «معمولا» دقیق نیست. پیشنهاد می‌کنم برای دقیق‌تر گفتن ازش اینطور بنویسیم که در سی‌اس اینترنشیپ اسپرینت‌ها به صورت یک هفته‌ای تعریف شده‌اند.
@shab-sa

2025-01-20 13:21 UTC, zahra-ahangari commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +این قابلیت کمک می‌کند تا سریع‌تر بتوانید جلسات مورد نظر خود را پیدا کنید.
برای این قسمت و باقی قسمت‌های دیگه راجع به Azure برنامه‌ای برای اضافه کردن تصویر هم داریم؟
فکر می‌کنم خیلی گویاتر باشه که عکس هم اضافه بشه در بعضی مراحل.
راجع به اینکه روی کدوم قسمت‌ها عکس بهترش می‌کنه هم می‌تونیم بیشتر صحبت کنیم با هم.
@shab-sa

2025-01-20 13:21 UTC, zahra-ahangari commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +دسترسی لازم به Azure Board از طریق ایمیل Outlook شما فراهم شده است. لینکی که برایتان ارسال شده است، شما را مستقیماً به صفحه‌ی مربوط به برنامه CS Internship هدایت می‌کند. با کلیک بر روی این لینک، وارد
این لینکی که اینجا گفته شده بعدتر قراره اضافه بشه؟
@shab-sa

2025-01-27 08:23 UTC, zahra-ahangari commented on processes/documents/CSI - Meeting Coordination for Interns --farsi-ir.md
> +## جزئیات خاص و نکات تکمیلی
این قسمت رو دوست داشتم؛ عالی که این نکات رو آوردی.
@shab-sa

2025-01-27 08:30 UTC, zahra-ahangari commented
من باقی این داکیومنت رو خوندم. 
الان که تمام این فرایند رو یک‌جا دیدم فکر می‌کنم بهتر باشه قسمت‌های مربوط به توضیح هماهنگی و نحوه‌ی شرکت برای هر کدوم از جلساتِ فنی و کارگاه‌ها بهتره یه داکیومنت جدا بشن چون هر کدوم به طور مستقل دارن یه فرایند رو توضیح می‌دن. از طرفی برای داکیومنت‌کردن این فرایند برای هر کدوم از گام‌هایی که برای هماهنگی و شرکت در جلسات اینجا نوشته شده، احتیاج به عکس داریم که دقیق‌تر و گویاتر کنه توضیحات رو. اما دیگه برای هر کدومشون اینجا کامنت نذاشتم؛ چون هم این داکیومنت بیش از اندازه طولانی می‌شه و هم اینکه به نظرم این میزان جزئیات بهتره توی داکیومنت مخصوص به خود هر کدوم از اون فرایندها آورده بشه.

در نتیجه اینکه پیشنهادم اینه این قسمت‌های جزئی از این داکیومنت جدا بشن و هر کدوم یک داکیومنت مستقل بشن. توی این داکیومنت هم به طور خلاصه و چکیده از هر کدوم از این فرایندها گفته بشه و بعد ارجاع بدیم به داکیومنت به‌خصوص برای هر کدوم.

@shab-sa @Ali-Sdg90

2025-02-17 14:40 UTC, zahra-ahangari approved these changes

2025-02-17 14:44 UTC, zahra-ahangari commented
مرسی شبنم، خسته نباشی.
از لحاظ محتوایی اوکیه و approve کردم. اما بابت نام‌گذاری اسم فایل و Heading ها فکر می‌کنم باید یه سری تغییرات ریز روش انجام بشه.
من فعلا مرج می‌کنم همین رو که نسخه اولیه‌ش رو داشته باشیم و بعد اون تغییرات رو روش اعمال کنیم.
@shab-sa

2025-02-17 14:44 UTC, merged